#remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme 
title: Automating process of sourcing and recommending artists for events using Zapier.
description: False
show_downloads: False
theme: jekyll-theme-minimal
